---
sssd_packages:
  - ntpdate
  - adcli
  - realmd
  - krb5-user
  - samba-common-bin
  - samba-libs
  - samba-dsdb-modules
  - sssd
  - sssd-tools
  - libnss-sss
  - libpam-sss
  - packagekit
  - policykit-1
  - language-pack-es

command_obfuscate_ldap_pass: "sss_obfuscate --domain {{ domain }} --stdin << EOF
4dm1n
EOF"
